name: website deployment
on:
  workflow_dispatch:
#   push:
#     branches:
#       - main # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.81.0'
        # extended: true

    - name: Build
      run: hugo --minify

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Copy files to GCE
      run: gcloud compute scp --port=${{ secrets.PORT }} --zone=us-central1-f --recurse public/* my-instance-gfw:/opt/gfw/caddy/site/
      
#     - name: Deploy
#       uses: appleboy/scp-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         port: ${{ secrets.PORT }}
#         password: ${{ secrets.PASSWORD }}
#         source: "public/*"
#         target: "/opt/gfw/caddy/site"
#         strip_components: 1
